#name
name: AndroidBuild
#events or action point to start our workflow, it is a trigger
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

#define the job, which is build the APK
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run : ./gradlew build

      - name: Run unit tests with Gradle
        run: ./gradlew test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk